/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddAirline: typeof import('./src/components/AddAirline.vue')['default']
    AddCountry: typeof import('./src/components/AddCountry.vue')['default']
    AddEntry: typeof import('./src/components/AddEntry.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DeleteEntry: typeof import('./src/components/DeleteEntry.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
